# This configures label matching for PR's.
#
# The keys are labels, and the values are lists of minimatch patterns
# to which those labels apply.
#
# NOTE: This can only add labels, not remove them.
# NOTE: Due to YAML syntax limitations, patterns or labels which start
# with a character that is part of the standard YAML syntax must be
# quoted.
#
# Please keep the labels sorted and deduplicated.

"software package":
- all:  
  - changed-files:
    - any-glob-to-any-file: ['external/*']
  - base-branch: 'main'
"build target":
- all:  
  - changed-files:
    - any-glob-to-any-file: ['targets/*']
  - base-branch: 'main'
"live patch":
- all:  
  - changed-files:
    - any-glob-to-any-file: ['live-patch/*']
  - base-branch: 'main'
"CI":
- all:  
  - changed-files:
    - any-glob-to-any-file: ['userpatches/*']
  - base-branch: 'main'
