URL=https://packages.microsoft.com/repos/code
KEY="stable main main"
RELEASE=jammy:noble:resolute:bookworm:trixie:forky
TARGET=desktop
METHOD=aptly
INSTALL=code
GLOB="Name (% code), \$Version (>= 1.107.0)"
CHECKSUM=ignore
ARCH=armhf:arm64:amd64
REPOSITORY=BS
