URL="https://packages.microsoft.com/repos/edge"
KEY="stable main main"
RELEASE=bookworm:noble:resolute:trixie:forky
TARGET=desktop
METHOD=aptly
INSTALL=microsoft-edge-stable
GLOB="Name (% microsoft-edge-stable)"
CHECKSUM=ignore
ARCH=amd64
REPOSITORY=BS
