URL=http://dl.google.com/linux/chrome/deb/
KEY="stable main"
RELEASE=jammy:bookworm:noble:resolute:trixie:forky
TARGET=desktop
METHOD=aptly
INSTALL=google-chrome-stable
GLOB="Name (% google-chrome-stable)"
ARCH=amd64:arm64
REPOSITORY=BS
