URL=https://ppa.launchpadcontent.net/liujianfeng1994/rockchip-multimedia/ubuntu
KEY=noble
RELEASE=noble
TARGET=desktop
METHOD=aptly
INSTALL=libwidevinecdm0
GLOB="Name (% libwidevinecdm0)"
ARCH=arm64:armhf
REPOSITORY=BS
