name: Enable runners
on:
  workflow_dispatch:
    inputs:
      period:
        type: choice
        description: 'Availability time'
        options:
        - 50m
        - 170m
        - 350m
        default: 50m
      machine:
        type: choice
        description: 'Machine type'
        options:
        - cax21
        - cax31
        - cax41
        default: 'cax21'
      machine_count:
        type: choice
        description: 'Number of machines'
        options:
        - "2"
        - "4"
        - "8"
        default: '2'
      runners_count:
        type: choice
        description: 'Runners per machine'
        options:
        - "2"
        - "4"
        - "8"
        - "16"
        default: '4'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  Prepare:
    name: "Power cloud runners"
    outputs:
      matrix: ${{steps.machine-number.outputs.matrix}}
    runs-on: ubuntu-latest
    steps:

      - name: Determine changed kernels
        id: machine-number
        run: |
          echo "matrix=$(for x in $(seq -w 1 ${{ github.event.inputs.machine_count }}); do echo ${x}; done|jq -cnR '[inputs | select(length>0)]' | jq -c)" >> $GITHUB_OUTPUT
  Test:
    name: "DUT"
    runs-on: [igor]
    needs: Prepare
    if: ${{ needs.Prepare.outputs.matrix != '[]' && needs.Prepare.outputs.matrix != '' }}
    timeout-minutes: 60
    strategy:
      # max-parallel: 32
      fail-fast: false
      matrix:

        node: ${{fromJson(needs.Prepare.outputs.matrix)}}

    steps:

      - name: Runner clean
        run: echo "test"










  start:
    name: "Power On"
    needs: Test
    runs-on: ubuntu-latest
    steps:

      - name: Enable Hetzner Virtual Machines
        if: ${{ github.repository_owner == 'Armbian' }}
        uses: armbian/actions/hetzner@test
        with:
          action-type: enable
          machine-type: "${{ github.event.inputs.machine || 'cax21' }}"
          runners-count: "${{ github.event.inputs.runners_count || '4' }}"
          machine-count: "${{ github.event.inputs.machine_count || '2' }}"
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.ACCESS_TOKEN }}

  sleeping:
    name: "Sleeping"
    needs: start
    runs-on: ubuntu-latest
    steps:
     
      - name: Sleeping "${{ github.event.inputs.period }}"
        run: sleep "${{ github.event.inputs.period || '5m' }}"
 
  stop:
    if: always()
    name: "Power Off"
    needs: sleeping
    runs-on: ubuntu-latest
    steps:
     
      - name: Enable Hetzner Virtual Machines
        if: ${{ always() && github.repository_owner == 'Armbian' }}
        uses: armbian/actions/hetzner@test
        with:
          action-type: disable
          machine-type: "${{ github.event.inputs.machine || 'cax21' }}"
          runners-count: "${{ github.event.inputs.runners_count || '2' }}"
          machine-count: "${{ github.event.inputs.machine_count || '2' }}"
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
