name: Enable runners
on:
  workflow_dispatch:
    inputs:
      period:
        type: choice
        description: 'Availability time'
        options:
        - 5m
        - 50m
        - 170m
        - 350m
        default: 50m
      machine:
        type: choice
        description: 'Machine type'
        options:
        - cax21
        - cax31
        - cax41
        default: 'cax21'
      machine_count:
        type: choice
        description: 'Number of machines'
        options:
        - 2
        - 4
        - 8
        default: '2'
      runners_count:
        type: choice
        description: 'Runners per machine'
        options:
        - 2
        - 4
        - 8
        - 16
        default: '2'

jobs:

  start:
    name: "Power On"
    runs-on: ubuntu-latest
    steps:
     
      - name: Enable Hetzner Virtual Machines
        uses: armbian/actions/hetzner_on@main
        with:
          machine-type: "${{ github.event.inputs.machine || 'cax21' }}"
          runners-count: "${{ github.event.inputs.runners_count || '2' }}"
          machine-count: "${{ github.event.inputs.machine_count || '2' }}"
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.ACCESS_TOKEN }}

  sleeping:
    name: "Sleeping"
    needs: start
    runs-on: ubuntu-latest
    steps:
     
      - name: Sleeping
        run: sleep "${{ github.event.inputs.period || '5m' }}"
 
  stop:
    if: always()
    name: "Power Off"
    needs: sleeping
    runs-on: ubuntu-latest
    steps:
     
      - name: Enable Hetzner Virtual Machines
        if: always()
        uses: armbian/actions/hetzner_off@main
        with:
          machine-type: "${{ github.event.inputs.machine || 'cax21' }}"
          runners-count: "${{ github.event.inputs.runners_count || '2' }}"
          machine-count: "${{ github.event.inputs.machine_count || '2' }}"
          key: ${{ secrets.KEY_TORRENTS }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_TORRENTS }}
          hetzner_id: ${{ secrets.HETZNER_ONE }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
