name: Build Root Filesystem (cronjob)
on:
  repository_dispatch:
    types: ["armbian"]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        default: 'main'

  workflow_call:
#  schedule:
#    - cron: '0 3 * * *' # Scheduled runs every day at 3am UTC

concurrency:
  group: rootfs
  cancel-in-progress: true

jobs:

  Minimal:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'yes'
      desktop: 'no'
      variant: ''
      branch: "${{ github.event.inputs.branch || 'main' }}"

  Server:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'no'
      desktop: 'no'
      variant: ''
      branch: "${{ github.event.inputs.branch || 'main' }}"

  GUI1:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'no'
      desktop: 'yes'
      variant: ''
      branch: "${{ github.event.inputs.branch || 'main' }}"

  GUI2:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'no'
      desktop: 'yes'
      variant: '3dsupport'
      branch: "${{ github.event.inputs.branch || 'main' }}"

  GUI3:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'no'
      desktop: 'yes'
      variant: '3dsupport browsers'
      branch: "${{ github.event.inputs.branch || 'main' }}"

  GUI4:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'no'
      desktop: 'yes'
      variant: '3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop'    
      branch: "${{ github.event.inputs.branch || 'main' }}"

  GUI5:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/include.yml

    with:

      minimal: 'no'
      desktop: 'yes'
      variant: 'browsers chat desktop_tools editors email internet multimedia office programming remote_desktop'
      branch: "${{ github.event.inputs.branch || 'main' }}"
