name: Upload live patch script
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'live-patch/**.sh'
      - '.github/workflows/live-patch.yml'

jobs:

  Teamcheck:
    permissions:
      actions: write
      
    name: "Check ORG Team Membership"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: [Linux, X64]
    steps:

    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit

    - name: "Check membership"
      uses: armbian/actions/team-check@2fa6c514d602b291fdc4dac1081fe4610ee0b376 # main
      with:
        ORG_MEMBERS: ${{ secrets.ORG_MEMBERS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEAM: "Release manager"

  Sign:
    needs: Teamcheck
    name: "Signing script"
    runs-on: ubuntu-latest
    steps:

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Import GPG key
        env:
          GPG_KEY1: ${{ secrets.GPG_KEY1 }}
        if: env.GPG_KEY1 != null
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_KEY1 }}
          passphrase: ${{ secrets.GPG_PASSPHRASE1 }}

      - name: Sign
        env:
          GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
        if: env.GPG_PASSPHRASE1 != null
        run: |

          for file in live-patch/*.sh;
          do
              cp $file $file.txt # to have web friendly version 
              echo ${{ secrets.GPG_PASSPHRASE1 }} | gpg --passphrase-fd 0 --armor --detach-sign --pinentry-mode loopback --batch --yes "$file"
          done

      - name: Install SSH key
        uses: shimataro/ssh-key-action@87a8f067114a8ce263df83e9ed5c849953548bc3 # v2.8.1
        with:
          key: ${{ secrets.KEY_UPLOAD }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_ARMBIAN_UPLOAD }}
          if_key_exists: replace

      - name: Upload
        run: |

          rsync --exclude "README.md" -avh -e "ssh -p 10023 -o StrictHostKeyChecking=accept-new" live-patch/* upload@rsync.armbian.com:/storage/www/dl/_patch/ --delete
